os:
  - linux

language: node_js

node_js:
  - 10

jobs:
  include:
    - stage: test
      script:
        - npm run lint
      script:
        - npm run build
        - npm run test

    - stage: release
      node_js: lts/*
      script:
        - npm run build
        - npm run semantic-release
