name: 'Lint'
description: 'Lint'
runs:
  using: 'composite'
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Update NPM registry
      run: npm run registry
      shell: bash

    - name: Install Dependencies
      run: npm install
      shell: bash

    - name: Lint Check
      run: npm run lint
      shell: bash
