name: 'Lint'
description: 'Lint'
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      run: npm install
      shell: bash

    - name: Lint Check
      run: npm run lint
      shell: bash
