name: 'Setup Release'
description: 'Setup Release'
inputs:
  token:
    description: 'The GitHub token required.'
  npm-token:
    description: 'The NPM authentication token required to publish.'
runs:
  using: 'composite'
  steps:
    - name: Git Identity
      run: |
        git config --global user.name 'baopso'
        git config --global user.email 'Group.CH_Open-Source@baloise.ch'
        git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Update NPM registry
      run: npm run registry
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build
      run: npm run build:force
      shell: bash
      env:
        BAL_DS_RELEASE: true

    - name: Create .npmrc
      run: |
        cat << EOF > "$HOME/.npmrc"
          //registry.npmjs.org/:_authToken=$NPM_TOKEN
        EOF
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
