name: 'Cypress E2E'
description: 'Cypress E2E'
runs:
  using: 'composite'
  steps:
    - name: List files in the repository
      run: ls .
      shell: bash

    - name: List files in the repository
      run: ls test
      shell: bash

    - name: List files in the repository
      run: ls test/cypress
      shell: bash

    - name: List files in the repository
      run: ls test/cypress/snapshots
      shell: bash

    - name: Run Cypress
      uses: cypress-io/github-action@v5
      with:
        start: npm run cy:start
        wait-on: 'http://localhost:3333'
        working-directory: test
        install: false
        browser: chrome
        env: type=actual
      env:
        SPLIT: ${{ strategy.job-total }}
        SPLIT_INDEX: ${{ strategy.job-index }}

    - name: List files in the repository
      if: failure()
      run: ls .
      shell: bash

    - name: List files in the repository
      if: failure()
      run: ls test
      shell: bash

    - name: List files in the repository
      if: failure()
      run: ls test/cypress
      shell: bash

    - name: List files in the repository
      if: failure()
      run: ls test/cypress/snapshots
      shell: bash

    - name: List files in the repository
      if: failure()
      run: ls test/cypress/snapshots/actual
      shell: bash

    - name: List files in the repository
      if: failure()
      run: ls test/cypress/snapshots/diff
      shell: bash

    - name: Report Visual Failures
      if: failure()
      working-directory: ./test
      run: npm run cy:visual:report
      shell: bash

    - name: Upload snapshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-snapshots-components-${{ strategy.job-index }}
        path: test/cypress/snapshots
