name: 'Cypress E2E'
description: 'Cypress E2E'
runs:
  using: 'composite'
  steps:
    - name: Run split Cypress tests 🧪
      uses: cypress-io/github-action@v5
      with:
        start: npm run cy:start
        wait-on: 'http://localhost:3333'
        working-directory: test
        install: false
        browser: chrome
      env:
        SPLIT: ${{ strategy.job-total }}
        SPLIT_INDEX: ${{ strategy.job-index }}

    - name: Upload snapshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-snapshots-components
        path: packages/components/cypress/snapshots
