name: 'Cypress E2E'
description: 'Cypress E2E'
runs:
  using: 'composite'
  steps:
    - name: Run Cypress
      uses: cypress-io/github-action@v5
      with:
        start: npm run cy:start
        wait-on: 'http://localhost:3333'
        working-directory: test
        install: false
        browser: chrome
        env: type=actual
      env:
        SPLIT: ${{ strategy.job-total }}
        SPLIT_INDEX: ${{ strategy.job-index }}

    - name: List files in the repository
      if: failure()
      run: ls ./test/cypress/snapshots
      shell: bash

    - name: List files in the repository
      if: failure()
      run: ls ./test/cypress/snapshots/actual
      shell: bash

    - name: List files in the repository
      if: failure()
      run: ls ./test/cypress/snapshots/diff
      shell: bash

    # - name: Report Visual Failures
    #   if: failure()
    #   working-directory: ./test
    #   run: npm run cy:visual:report
    #   shell: bash

    # - name: Upload snapshots
    #   if: always()
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: cypress-snapshots-components-actual-${{ strategy.job-index }}
    #     path: test/cypress/snapshots/actual

    # - name: Upload snapshots
    #   if: always()
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: cypress-snapshots-components-diff-${{ strategy.job-index }}
    #     path: test/cypress/snapshots/diff

    - uses: ./.github/workflows/actions/upload-archive
      if: failure()
      with:
        name: test-e2e-actual-${{ strategy.job-index }}
        output: test/cypress/snapshots/UpdatedScreenshots-Actual-${{ strategy.job-index }}.zip
        paths: test/cypress/snapshots/actual

    - uses: ./.github/workflows/actions/upload-archive
      if: failure()
      with:
        name: test-e2e-diff-${{ strategy.job-index }}
        output: test/cypress/snapshots/UpdatedScreenshots-Diff-${{ strategy.job-index }}.zip
        paths: test/cypress/snapshots/diff
