name: 'Build E2E'
description: 'Build E2E'
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      run: npm ci
      shell: bash

    - name: Build
      run: npm run ci:build:e2e
      shell: bash

    - uses: ./.github/workflows/actions/upload-archive
      with:
        name: test-e2e
        output: test/TestE2eBuild.zip
        paths: test/generated
