name: 'Test Angular'
description: 'Test Angular'
inputs:
  app:
    description: 'The specific test application'
runs:
  using: 'composite'
  steps:
    - name: Run Cypress tests 🧪
      uses: cypress-io/github-action@v5
      with:
        start: npm run cy:start
        wait-on: 'http://localhost:4200'
        working-directory: apps/angular/${{ inputs.app }}
        install: false
        browser: chrome

    - name: Upload snapshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-snapshots-angular-${{ inputs.app }}
        path: apps/angular/${{ inputs.app }}/cypress/snapshots

