name: 'Angular Setup v16'
description: 'Angular Setup v16'
runs:
  using: 'composite'
  steps:
    - name: Disable Husky
      run: npm pkg delete scripts.prepare
      shell: bash

    - uses: ./.github/workflows/actions/download-archive
      with:
        name: components-dist
        path: ./packages/components
        filename: ComponentsDist.zip

    - uses: ./.github/workflows/actions/download-archive
      with:
        name: components-loader
        path: ./packages/components
        filename: ComponentsLoader.zip

    - name: Install Dependencies
      run: npm ci
      working-directory: ./apps/angular/v16
      shell: bash

    - name: Post Install
      run: npm run postinstall
      working-directory: ./apps/angular/v16
      shell: bash

    - name: Install Cypress
      run: npm run cy:install
      working-directory: ./apps/angular/v16
      shell: bash

    - name: Build Angular App
      run: npm run build
      working-directory: ./apps/angular/v16
      shell: bash
