name: Continuous

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 👷 Build Design System
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/build

  docs:
    name: 📝 Build Documentation
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/build-docs

  format:
    name: 🚨 Verify Code Format
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/format

  spell:
    name: 🚨 Spell Checking
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/spell

  lint:
    name: 🚨 Analyze Code
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
      HUSKY: 0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/lint

  test:
    name: 🧪 Unit Tests
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
      HUSKY: 0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/test

  test-components:
    name: 🧪 Component Tests
    runs-on: ubuntu-22.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
      HUSKY: 0
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/test-setup
      - uses: ./.github/workflows/actions/test-components

  test-angular:
    name: 🧪 Angular Tests
    runs-on: ubuntu-22.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
      HUSKY: 0
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/test-angular-setup
      - uses: ./.github/workflows/actions/test-angular

  test-e2e:
    name: 🧪 E2E Tests
    runs-on: ubuntu-22.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
      HUSKY: 0
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/test-setup
      - uses: ./.github/workflows/actions/test-e2e

  test-e2e-report:
    name: 📈 E2E Tests Report
    runs-on: ubuntu-22.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
      HUSKY: 0
    if: ${{ always() }}
    needs: [test-e2e]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/test-e2e-report
