name: Documentation

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  Publish:
    name: 📝 Publish Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/docs
        with:
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
          incubator_github_user: ${{ secrets.INCUBATOR_GITHUB_USER }}
          incubator_github_token: ${{ secrets.INCUBATOR_GITHUB_TOKEN }}
