name: Documentation

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  Publish:
    name: 📝 Publish Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/docs
