name: Continuous@3

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 👷 Build Design System
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/build

  format:
    name: 🚨 Verify Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/format

  spell:
    name: 🚨 Verify Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/spell

  lint:
    name: 🚨 Analyzing Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/lint

  test:
    name: 🧪 Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/test

  test-e2e:
    name: 🧪 E2E Tests
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/test-setup
      - uses: ./.github/workflows/actions/test-e2e

  test-components:
    name: 🧪 Component Tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/test-setup
      - uses: ./.github/workflows/actions/test-components
