name: Snapshot Release

on:
  workflow_dispatch:

jobs:
  Release:
    name: 🚀 Release Snapshot
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/actions/setup-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Release snapshot
        run: |
          npx changeset version --snapshot snapshot
          npx changeset publish --no-git-tag --tag snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        shell: bash

      - name: Git Reset
        run: git reset --hard
        shell: bash
