name: Visual All Regression Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 👷 Build Design System
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/build

  screenshots:
    name: 📸 Updating Screenshots
    runs-on: ubuntu-22.04
    needs: [build]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
      HUSKY: 0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: ./.github/workflows/actions/setup
      - uses: ./.github/workflows/actions/test-setup

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          start: npm run cy:start
          wait-on: 'http://localhost:3333'
          working-directory: test
          install: false
          browser: chrome
          env: type=base
          spec: |
            cypress/e2e/visual/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: test/cypress/snapshots

      - name: Commit base images
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore(): update base images'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
